CrudMVC/Models/ApplicationDbContext.cs
using System;
using Microsoft.EntityFrameworkCore;

namespace CrudMVC.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }

        public DbSet<Orders> Orders {get; set;}

        public DbSet<Products> Products { get; set; }

        public DbSet<Cart> Cart { get; set; }
    }
}

CrudMVC/Models/Cart.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CrudMVC.Models
{
    public class Cart
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string SKU { get; set; }
        public string Description { get; set; }
        public int Quantity { get; set; }
        public double UnitPrice { get; set; }
        public double TotalPrice { get; set; }

        public Cart()
        {
        }
    }
}

CrudMVC/Models/ErrorViewModel.cs
using System;

namespace CrudMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrudMVC/Models/Orders.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CrudMVC.Models
{
    public class Orders
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string OrderDesc { get; set; }
        [Required]
        public string SKU { get; set; }
        public string SKUDescr { get; set; }
        public int Qty { get; set; }
        public double LineCost { get; set; }
        public double OrderCost { get; set; }
        public string Status { get; set; }

        public Orders()
        {
        }

    }
}

CrudMVC/Models/Products.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CrudMVC.Models
{
    public class Products
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string SKU { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public double Price { get; set; }
        public int AvailableQty { get; set; }

        public Products()
        {
        }
    }
}

CrudMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CrudMVC.Models;

namespace CrudMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CrudMVC/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CrudMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CrudMVC.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public Orders Orders { get; set; }

        public OrdersController(ApplicationDbContext db)
        {
            _db = db;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        #region API Calls
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.Orders.ToListAsync() });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var orderFromDb = await _db.Orders.FirstOrDefaultAsync(u => u.Id == id);
            if (orderFromDb == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            _db.Orders.Remove(orderFromDb);
            await _db.SaveChangesAsync();
            return Json(new { success = true, message = "Delete successful" });
        }

        #endregion

    }
}

CrudMVC/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CrudMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CrudMVC.Controllers
{
    public class ProductsController : Controller
    {
        private string _UsrMsg;
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public Products Product { get; set; }

        public ProductsController(ApplicationDbContext db)
        {
            _db = db;
        }

        // GET: /<controller>/
        public async Task<IActionResult> IndexAsync()
        {
            var myProducts = await _db.Products.ToListAsync();
            return View(myProducts);
        }

        public IActionResult Upsert(int? id)
        {
            Product = new Products();
            if (id == null)
            {
                //Create Action
                return View(Product);
            }
            //Edit Action
            Product = _db.Products.FirstOrDefault(u => u.Id == id); //Searching for a specific product
            if (Product == null) //If there is no product returned
            {
                return NotFound();
            }
            return View(Product); //Return the products that's found
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert() //To handle the Post action
        {
            if (ModelState.IsValid)
            {
                _UsrMsg = "";
                if (Product.Id == 0)
                {
                    //Create Book
                    _db.Products.Add(Product);
                    _UsrMsg = "Add Successful";
                }
                else
                {
                    //Update Book
                    _db.Products.Update(Product);
                    _UsrMsg = "Update Successful";
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Product);
        }

        public IActionResult OnGet()
        {
            return View(Product);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            _UsrMsg = "";
            var productFromDb = await _db.Products.FirstOrDefaultAsync(u => u.Id == id);
            if (productFromDb == null)
            {
                _UsrMsg = "Error while Deleting";
            }
            _db.Products.Remove(productFromDb);
            await _db.SaveChangesAsync();
            _UsrMsg = "Delete Successful";
            return RedirectToAction("Index");
        }
    }
}

CrudMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CrudMVC/Views/Orders/Index.cshtml
<br />
<div class="container row p-0 m-0">
    <div class="col-6">
        <h2 class="text-info">Orders List</h2>
    </div>
    <div class="col-12 border p-3">
        <table id="DT_loadOrders" class="table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Description</th>
                    <th>Total Cost</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

@section Scripts{
    <script src="~/js/orderList.js"></script>
}

CrudMVC/Views/Products/Index.cshtml
<br />
<div class="container row p-0 m-0">
    <div class="col-6">
        <h2 class="text-info">List of Products</h2>
    </div>
    <div class="col-3 offset-3">
        <a asp-action="Upsert" asp-controller="Products" class="btn btn-info form-control text-white">
        Add New Product</a>
    </div>
    <div class="col-12 border p-3">
        <table id="DT_loadProducts" class="table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>SKU</th>
                    <th>Description</th>
                    <th>Cost</th>
                    <th>Stock Units</th>
                    <td></td>
                </tr>
            </thead>

            @if (Model != null)
            {
                foreach (Products item in Model)
                {
                    <tr>
                        <td>
                            @item.SKU
                        </td>
                        <td>
                            @item.Description
                        </td>
                        <td>
                            @item.Price
                        </td>
                        <td>
                            @item.AvailableQty
                        </td>
                        <td>
                            <form asp-action="Delete" method="post" asp-route-id="@item.Id">
                                <button asp-controller="Products" asp-action="Upsert" asp-route-id="@item.Id" class="btn btn-success text-white">Edit</button>
                                <button class="btn btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                    }
                }
            
        </table>
    </div>
</div>

CrudMVC/Views/Products/Upsert.cshtml
@model CrudMVC.Models.Products;


<br />
<h2 class="text-info">@(Model.Id != 0 ? "Edit" : "Create") Product</h2>
<br />

<div class="border container" style="padding:30px">
    <form method="post">
        @if (Model.Id != 0)
        {
            <input type="hidden" asp-for="Id" />
        }
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="SKU"></label>
            </div>
            <div class="col-6">
                <input asp-for="SKU" class="form-control" />
                <span asp-validation-for="SKU" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Description"></label>
            </div>
            <div class="col-6">
                <input asp-for="Description" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Price"></label>
            </div>
            <div class="col-6">
                <input asp-for="Price" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="AvailableQty">Units in Stock</label>
            </div>
            <div class="col-6">
                <input asp-for="AvailableQty" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3 offset-3">
                <button type="submit" class="btn btn-primary form-control">
                    @(Model.Id !=0 ? "Update" : "Create")
                </button>
            </div>
            <div class="col-3">
                <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

CrudMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mississipi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CrudMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Product Maintenance</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Order Management</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CrudMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>